-- Deploy omlpi:0001-data to pg
-- requires: 0000-locales

BEGIN;

CREATE TABLE area (
    id INT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

INSERT INTO area (id, name) VALUES (1, 'Assistência Social'), (2, 'Educação'), (3, 'Saúde');

CREATE TABLE indicator (
    id          INT PRIMARY KEY,
    description TEXT NOT NULL UNIQUE,
    area_id     INT NOT NULL REFERENCES area(id),
    base        TEXT
);

CREATE TABLE subindicator (
    id INT NOT NULL PRIMARY KEY,
    description TEXT NOT NULL,
    classification TEXT NOT NULL
);

CREATE TABLE indicator_locale (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_id   INT NOT NULL REFERENCES indicator(id),
    locale_id      INT NOT NULL REFERENCES locale(id),
    year           INT NOT NULL,
    value_relative TEXT,
    value_absolute TEXT,
    UNIQUE(indicator_id, locale_id, year)
);

CREATE TABLE subindicator_locale (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_id    INT NOT NULL REFERENCES indicator(id),
    subindicator_id INT NOT NULL REFERENCES subindicator(id),
    locale_id      INT NOT NULL REFERENCES locale(id),
    year            INT NOT NULL,
    value_relative  TEXT,
    value_absolute  TEXT,
    UNIQUE(subindicator_id, indicator_id, locale_id, year)
);

COMMIT;