-- Deploy omlpi:0003-plan-upload to pg
-- requires: 0002-locale-latlong

BEGIN;

CREATE TABLE plan_upload (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           TEXT NOT NULL,
  email          TEXT NOT NULL,
  locale_id      INT NOT NULL REFERENCES locale(id),
  filename       TEXT NOT NULL,
  sha256_digest  TEXT NOT NULL,
  created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

COMMIT;
