-- Deploy omlpi:0007-add-config to pg
-- requires: 0006-change-plan-upload-fields

BEGIN;

CREATE TABLE config (
    id int generated by default as identity primary key,
    name character varying NOT NULL,
    value character varying NOT NULL,
    valid_from timestamp without time zone DEFAULT now() NOT NULL,
    valid_to timestamp without time zone DEFAULT 'infinity'::timestamp without time zone NOT NULL
);

CREATE UNIQUE INDEX idx_config_key ON config USING btree (name) WHERE (valid_to = 'infinity'::timestamp without time zone);

COMMIT;
