-- Deploy omlpi:0008-add-ods to pg
-- requires: 0007-add-config

BEGIN;

create table ods (
    id int generated by default as identity primary key,
    name text not null,
    filename text
);

insert into ods (id, name)
values
  (1, 'Erradicação da Pobreza'),
  (2, 'Fome Zero e Agricultura Sustentável'),
  (3, 'Saúde e Bem-Estar'),
  (4, 'Educação de Qualidade'),
  (5, 'Igualdade de Gênero'),
  (6, 'Água potável e Saneamento'),
  (7, 'Energia Limpa e Acessível'),
  (8, 'Trabalho Decente e Crescimento Econômico'),
  (9, 'Indústria, Inovação e Infraestrutura'),
  (10, 'Redução das Desigualdades'),
  (11, 'Cidades e Comunidades Sustentáveis'),
  (12, 'Consumo e Produção Responsáveis'),
  (13, 'Ação Contra a Mudança Global do Clima'),
  (14, 'Vida na Água'),
  (15, 'Vida Terrestre'),
  (16, 'Paz, Justiça e Instituições Eficazes'),
  (17, 'Parcerias e Meios de Implementação');

update ods set filename = 'ods-' || id || '.png';
alter table ods alter column filename set not null;

alter table indicator
  add column ods int[];

COMMIT;
